### ISSUE TITLE
New strategy for the AI.

### ISSUE THREAD

**Issue by abvg9** [notaphplover/catan-heroes#23]
Implement a deterministic subject distribution system as agreed.

**Comment by notaphplover** [comment]
This issue is related to the production generation algorithm which is detailed right now:

Given a set of dice rolls (default 2), given a dice face amount (default 6):

1. Build the set of dice rolls. The set size should be `dice_face_amount ^ rolls`.
2. Build the set of sum of dice rolls.
3. Create a list taking random entries of the sum set until no entries remain in the set. 

The production number at the `i`-th turn with a list `l` of size `s` is `l[i % s]`
